CRITICAL - 2024-05-10 03:33:45 --> Error: Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-05-10 03:33:46 --> ErrorException: Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php:74
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#6 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\spark(88): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 03:35:25 --> Error: Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-05-10 03:35:25 --> ErrorException: Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php:74
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#6 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\spark(88): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 03:38:23 --> Error: Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-05-10 03:38:23 --> ErrorException: Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php:74
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#6 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\spark(88): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-10 03:41:47 --> Error: Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-05-10 03:41:47 --> ErrorException: Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php:74
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#6 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\spark(88): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-05-10 01:52:51 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pa...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 01:52:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 01:52:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$3vof5dOdv0EAOchqM3NjHe5edlaqiOlB2q1He1IAli5zrVvfIsRFG\', \'2024-05-10 01:52:51\', \'2024-05-10 01:52:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$3vof5dOdv0EAOchqM3NjHe5edlaqiOlB2q1He1IAli5zrVvfIsRFG\', \'2024-05-10 01:52:51\', \'2024-05-10 01:52:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 01:52:52 --> [Caused by] mysqli_sql_exception: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$3vof5dOdv0EAOchqM3NjHe5edlaqiOlB2q1He1IAli5zrVvfIsRFG\', \'2024-05-10 01:52:51\', \'2024-05-10 01:52:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$3vof5dOdv0EAOchqM3NjHe5edlaqiOlB2q1He1IAli5zrVvfIsRFG\', \'2024-05-10 01:52:51\', \'2024-05-10 01:52:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$3vof5dOdv0EAOchqM3NjHe5edlaqiOlB2q1He1IAli5zrVvfIsRFG\', \'2024-05-10 01:52:51\', \'2024-05-10 01:52:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 01:54:50 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pa...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 01:54:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 01:54:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$UZq112WgRoDTI85UajdXceOAvmhUf8SmBBy778fW5wy53LiFiwBQS\', \'2024-05-10 01:54:50\', \'2024-05-10 01:54:50\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$UZq112WgRoDTI85UajdXceOAvmhUf8SmBBy778fW5wy53LiFiwBQS\', \'2024-05-10 01:54:50\', \'2024-05-10 01:54:50\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 01:54:50 --> [Caused by] mysqli_sql_exception: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$UZq112WgRoDTI85UajdXceOAvmhUf8SmBBy778fW5wy53LiFiwBQS\', \'2024-05-10 01:54:50\', \'2024-05-10 01:54:50\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$UZq112WgRoDTI85UajdXceOAvmhUf8SmBBy778fW5wy53LiFiwBQS\', \'2024-05-10 01:54:50\', \'2024-05-10 01:54:50\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$UZq112WgRoDTI85UajdXceOAvmhUf8SmBBy778fW5wy53LiFiwBQS\', \'2024-05-10 01:54:50\', \'2024-05-10 01:54:50\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 02:00:52 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pa...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 02:00:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:00:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$GAPWpvPTq5T/UQQBTyTrNeUOYABZorlSxBZLNxMQVngGvJaONdWTu\', \'2024-05-10 02:00:52\', \'2024-05-10 02:00:52\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$GAPWpvPTq5T/UQQBTyTrNeUOYABZorlSxBZLNxMQVngGvJaONdWTu\', \'2024-05-10 02:00:52\', \'2024-05-10 02:00:52\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:00:52 --> [Caused by] mysqli_sql_exception: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$GAPWpvPTq5T/UQQBTyTrNeUOYABZorlSxBZLNxMQVngGvJaONdWTu\', \'2024-05-10 02:00:52\', \'2024-05-10 02:00:52\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$GAPWpvPTq5T/UQQBTyTrNeUOYABZorlSxBZLNxMQVngGvJaONdWTu\', \'2024-05-10 02:00:52\', \'2024-05-10 02:00:52\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$GAPWpvPTq5T/UQQBTyTrNeUOYABZorlSxBZLNxMQVngGvJaONdWTu\', \'2024-05-10 02:00:52\', \'2024-05-10 02:00:52\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 02:01:19 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pa...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 02:01:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:01:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$oYfFowMkhIZj/eXHuEoqfOEx3gyDO9Ntlez0DpuHRDKux47oX8qMe\', \'2024-05-10 02:01:19\', \'2024-05-10 02:01:19\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$oYfFowMkhIZj/eXHuEoqfOEx3gyDO9Ntlez0DpuHRDKux47oX8qMe\', \'2024-05-10 02:01:19\', \'2024-05-10 02:01:19\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:01:19 --> [Caused by] mysqli_sql_exception: Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$oYfFowMkhIZj/eXHuEoqfOEx3gyDO9Ntlez0DpuHRDKux47oX8qMe\', \'2024-05-10 02:01:19\', \'2024-05-10 02:01:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$oYfFowMkhIZj/eXHuEoqfOEx3gyDO9Ntlez0DpuHRDKux47oX8qMe\', \'2024-05-10 02:01:19\', \'2024-05-10 02:01:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$oYfFowMkhIZj/eXHuEoqfOEx3gyDO9Ntlez0DpuHRDKux47oX8qMe\', \'2024-05-10 02:01:19\', \'2024-05-10 02:01:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `parqueadero` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 02:05:08 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 02:05:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:05:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$wp4Gs4d/fXMLPeWP96u/IeYSGYId5ANEKann7GmlL03OCV0f2IOqe\', \'2024-05-10 02:05:08\', \'2024-05-10 02:05:08\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$wp4Gs4d/fXMLPeWP96u/IeYSGYId5ANEKann7GmlL03OCV0f2IOqe\', \'2024-05-10 02:05:08\', \'2024-05-10 02:05:08\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:05:08 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$wp4Gs4d/fXMLPeWP96u/IeYSGYId5ANEKann7GmlL03OCV0f2IOqe\', \'2024-05-10 02:05:08\', \'2024-05-10 02:05:08\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$wp4Gs4d/fXMLPeWP96u/IeYSGYId5ANEKann7GmlL03OCV0f2IOqe\', \'2024-05-10 02:05:08\', \'2024-05-10 02:05:08\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$wp4Gs4d/fXMLPeWP96u/IeYSGYId5ANEKann7GmlL03OCV0f2IOqe\', \'2024-05-10 02:05:08\', \'2024-05-10 02:05:08\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 02:13:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 02:13:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:13:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$8fNCeezAJLlJef7au3jenO8V04/EikWHj8hPC2DX0GjYvnyCG1RuK\', \'2024-05-10 02:13:37\', \'2024-05-10 02:13:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$8fNCeezAJLlJef7au3jenO8V04/EikWHj8hPC2DX0GjYvnyCG1RuK\', \'2024-05-10 02:13:37\', \'2024-05-10 02:13:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:13:37 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$8fNCeezAJLlJef7au3jenO8V04/EikWHj8hPC2DX0GjYvnyCG1RuK\', \'2024-05-10 02:13:37\', \'2024-05-10 02:13:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$8fNCeezAJLlJef7au3jenO8V04/EikWHj8hPC2DX0GjYvnyCG1RuK\', \'2024-05-10 02:13:37\', \'2024-05-10 02:13:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$8fNCeezAJLlJef7au3jenO8V04/EikWHj8hPC2DX0GjYvnyCG1RuK\', \'2024-05-10 02:13:37\', \'2024-05-10 02:13:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 02:15:48 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 02:15:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:15:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$JBEjqFLFBJdB20OxUULcPOsdWVDo8Wpxl70vgdeu4MBdQeCNKRg4W\', \'2024-05-10 02:15:48\', \'2024-05-10 02:15:48\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$JBEjqFLFBJdB20OxUULcPOsdWVDo8Wpxl70vgdeu4MBdQeCNKRg4W\', \'2024-05-10 02:15:48\', \'2024-05-10 02:15:48\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:15:48 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$JBEjqFLFBJdB20OxUULcPOsdWVDo8Wpxl70vgdeu4MBdQeCNKRg4W\', \'2024-05-10 02:15:48\', \'2024-05-10 02:15:48\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$JBEjqFLFBJdB20OxUULcPOsdWVDo8Wpxl70vgdeu4MBdQeCNKRg4W\', \'2024-05-10 02:15:48\', \'2024-05-10 02:15:48\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$JBEjqFLFBJdB20OxUULcPOsdWVDo8Wpxl70vgdeu4MBdQeCNKRg4W\', \'2024-05-10 02:15:48\', \'2024-05-10 02:15:48\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
ERROR - 2024-05-10 02:18:56 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\app\Controllers\Register.php(27): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Register->index()
#10 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#11 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PROYECTO-API\PROYECTO-API\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-10 02:18:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:18:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$MBz9AbtftKCokQVJVd7sZeYkb5dqgG.Jfh0vmBP4Ad4KM3uwfV36G\', \'2024-05-10 02:18:56\', \'2024-05-10 02:18:56\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$MBz9AbtftKCokQVJVd7sZeYkb5dqgG.Jfh0vmBP4Ad4KM3uwfV36G\', \'2024-05-10 02:18:56\', \'2024-05-10 02:18:56\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
CRITICAL - 2024-05-10 02:18:56 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$MBz9AbtftKCokQVJVd7sZeYkb5dqgG.Jfh0vmBP4Ad4KM3uwfV36G\', \'2024-05-10 02:18:56\', \'2024-05-10 02:18:56\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$MBz9AbtftKCokQVJVd7sZeYkb5dqgG.Jfh0vmBP4Ad4KM3uwfV36G\', \'2024-05-10 02:18:56\', \'2024-05-10 02:18:56\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (\'juan@gmail.com\', \'$2y$10$MBz9AbtftKCokQVJVd7sZeYkb5dqgG.Jfh0vmBP4Ad4KM3uwfV36G\', \'2024-05-10 02:18:56\', \'2024-05-10 02:18:56\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`email`, `password`, `created_at`, `updated_at`) VALUES (:email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Register.php(27): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Register->index()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PROYECTO-API\\PROYECTO-API\\public\\index.php')
